# Site settings
title: My resume
email: resume@gladis.org
description: ""
baseurl: ""
url: "https://resume.gladis.org"
twitter_username: hwmrocker
github_username:  hwmrocker

# Build settings
markdown: kramdown
permalink: pretty
